apiVersion: v1
kind: Service
metadata:
  name: nginx-conm-svc
  namespace: std
spec:
  type: NodePort
  selector:
    app: nginx-conm
  ports:
    - protocol: TCP
      port: 81
      targetPort: 80
      nodePort: 30009