apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-hostpath
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-hostpath
  template:
    metadata:
      labels:
        app: nginx-hostpath
    spec:
      containers:
      - name: nginx-hostpath
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: hostpath-data
          mountPath: /data
      volumes:
      - name: hostpath-data
        hostPath:
          path: /home/begoingtodev/k8s-begoingto/volumes/data # This is the path on the host machine of node name