apiVersion: v1
kind: Secret
metadata:
  name: nexus-secret
  namespace: nexus
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: >-
    ewogICAgImF1dGhzIjogewogICAgICAgICJuZC5iZWdvaW5nZGV2Lm1lIjogewogICAgICAgICAgInVzZXJuYW1lIjogImRvY2tlci1yZXBvIiwKICAgICAgICAgICJwYXNzd29yZCI6ICIxMjMiLAogICAgICAgICAgImVtYWlsIjogImRvY2tlckBnbWFpbC5jb20iLCAKICAgICAgICAgICJhdXRoIjogIlpHOWphMlZ5TFhKbGNHODZNVEl6IgogICAgICAgIH0KICAgIH0KfQ==