apiVersion: apps/v1
kind: Deployment
metadata:
  name: begoingto-deployment
  labels:
    app: begoingto-lbl
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: begoingto-lbl
  template:
    metadata:
      labels:
        app: begoingto-lbl
    spec:
      containers:
      - name: begoingto-doc
        image: begoingto/begoingto-doc:0.0.1
        ports:
        - containerPort: 3000
# create service for deploument
---
apiVersion: v1
kind: Service
metadata:
  name: begoingto-svc
  labels:
    app: begoingto-lbl
spec:
  type: NodePort
  selector:
    app: begoingto-lbl
  ports:
    - protocol: TCP
      port: 3003
      targetPort: 3000
      nodePort: 30005