---
- name: A create directory nsf
  hosts: all
  become: yes
  tasks:
    - name: create nfs directory
      file:
        path: /opt/nfs/data2
        state: directory
        mode: 0777
        group: nogroup
        owner: nobody

    - name: install nfs-common
      apt:
        update_cache: yes
        name: nfs-common
        state: present
      when: "'workers' in group_names"

    - name: install nfs-kernel-server
      apt:
        update_cache: yes
        name: nfs-kernel-server
        state: present
      when: "'masters' in group_names"

    - name: Check if nfs-kernel-server is installed
      command: dpkg -l | grep nfs-kernel-server
      register: nfs_kernel_installed
      changed_when: false
      failed_when: false
      check_mode: false
      when: "'workers' in group_names"

    - name: uninstall nfs-kernel-server in workers
      apt:
        update_cache: yes
        name: nfs-kernel-server
        state: absent
      when: 
        - "'workers' in group_names"
        - nfs_kernel_installed.rc == 0
    
    - name: Create list of ansible_host for all workers
      set_fact:
        # workers_ip_list: "{{ groups['workers'] | map('extract', hostvars) | map(attribute='ansible_host') | list }}" # using this when you ansible_host is private ip
        workers_ip_list: "{{ groups['all'] | map('extract', hostvars) | map(attribute='ansible_facts.default_ipv4.address') | list }}"  # using this when you get host private ip
      
    - name: Show the list of ansible_host for workers
      debug:
        var: workers_ip_list
      when: "'masters' in group_names"
    
    - name: Add specific IPs to NFS exports
      lineinfile:
        path: /etc/exports
        line: "/opt/nfs/data2 {{ item }}(rw,sync,no_subtree_check)"
        state: present
      loop: "{{ workers_ip_list }}"
      when: "'masters' in group_names"
      notify:
        - Export NFS

    - name: Allow all IPs to access NFS (for demonstration purposes - not recommended)
      lineinfile:
        path: /etc/exports
        line: "/opt/nfs/data2 *(rw,sync,no_subtree_check) # All IPs"
        state: present
      when: "'masters' in group_names"
      notify:
        - Export NFS

    - name: restart nfs-kernel-server
      service:
        name: nfs-kernel-server
        state: restarted
      when: "'masters' in group_names"

  handlers:
    - name: Export NFS
      ansible.builtin.command: exportfs -a
      become: yes