apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgsql-deployment
  namespace: stdsecret
  labels:
    app: pgsql-lbl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgsql-lbl
  template:
    metadata:
      labels:
        app: pgsql-lbl
    spec:
      containers:
      - name: pgsql-app
        image: postgres:16
        ports:
        - containerPort: 5432
        envFrom:
        - secretRef:
            name: postgres-secret
        # - name: POSTGRES_PASSWORD
          # value: "root@!23"