apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pgsql-begoingdev-me
  namespace: stdsecret
spec:
  rules:
    - host: pgsql.begoingdev.me
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pgsql-svc
                port:
                  number: 5435