apiVersion: v1
kind: Service
metadata:
  name: pgsql-svc
  namespace: stdsecret
spec:
  type: NodePort
  selector:
    app: pgsql-lbl
  ports:
    - protocol: TCP
      port: 5435
      targetPort: 5432
      nodePort: 30010