apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-hostpath
  namespace: pvc-hostpath
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: hostpath-sharing
  hostPath:
    path: /opt/nfs/data/hostpath