apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spring-pvc
  namespace: pvc-hostpath
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: hostpath-sharing # get form pv.yaml