apiVersion: v1
kind: PersistentVolume
metadata:
  name: spring-pv
  namespace: pvc
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-sharing
  nfs:
    server: 10.148.0.19
    path: /opt/nfs/data