apiVersion: v1
kind: Service
metadata:
  name: react-app
spec:
  type: NodePort
  selector:
    app: reactjs-replica
  ports:
    - protocol: TCP
      port: 3005
      targetPort: 80
      nodePort: 30005