apiVersion: v1
kind: Service
metadata:
  name: begoingto-svc
  labels:
    app: begoingto-lbl
spec:
  type: NodePort
  selector:
    app: begoingto-lbl
  ports:
    - protocol: TCP
      port: 3003
      targetPort: 3000
      nodePort: 30003