apiVersion: v1
kind: Service
metadata:
  name: react-service
spec:
  type: NodePort
  selector:
    app: react-pod
  ports:
    - protocol: TCP
      port: 3003
      targetPort: 80
      nodePort: 30003