apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nextjs-app
  labels:
    app: nextjs-lbl
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nextjs-lbl
  template:
    metadata:
      labels:
        app: nextjs-lbl
    spec:
      containers:
        - name: nextjs-app
          image: begoingto/nextjs-hostname:0.0.1
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: nextjs-svc
spec:
  type: NodePort
  selector:
    app: nextjs-lbl
  ports:
    - protocol: TCP
      port: 3008
      targetPort: 3000
      nodePort: 30007