---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-domain-ingress
  namespace: argocd
spec:
  rules:
    - host: argo.begoingdev.me
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: argocd-server
                port:
                  number: 80
